### ISSUE TITLE
1.1.0的package.json里导出的cjs文件在dist目录下没有

### ISSUE THREAD

**Issue by JiaLiu** [pengzhanbo/utils#1]
1.0.9无此问题。1.1.0的dist/cjs目录下的扩展名都是.js了？

**Comment by pengzhanbo** [comment]
我检查了一下，发现是由于 `unbuild` 升级到 `2.0.0` 后，`entries` 的 `builder` 为 `mkdist` 时，其 `options` 的 `ext` 在类型声明中不再支持 `cjs` 值，在autofix 时，替换为了 `js` ，

发现[unbuild diff](https://github.com/unjs/unbuild/commit/f40a889#diff-a0783de05a2fd57961d6af91272145b1a8e7a90db5e5c1576c6c81ca0c56dc4e) 更新了类型声明。

但是查找 [mkdist](https://github.com/unjs/mkdist/blob/main/src/loader.ts#L38C18-L38C18) 有发现其实是支持 `cjs` 的。
而且目前发现 其 `cjs` format 也没有正确生成 `d.cts` 的类型声明文件。 目前我先 把  ext 修改为 `cjs` 解决此问题。

后续我提 issue 给 `unbuild` 以及 `mkdist` 询问下。 或者 切换到 `tsx` `tsup` 等其他工具进行构建。
